# These are all the cops that are enabled in the default configuration.

AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  Enabled: false

AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

Alias:
  Description: 'Use alias_method instead of alias.'
  Enabled: false

AlignArray:
  Description: >-
                 Align the elements of an array literal if they span more than
                 one line.
  Enabled: false

AlignHash:
  Description: >-
                 Align the elements of a hash literal if they span more than
                 one line.
  Enabled: false

AlignParameters:
  Description: >-
                 Align the parameters of a method call if they span more
                 than one line.
  Enabled: false

AndOr:
  Description: 'Use &&/|| instead of and/or.'
  Enabled: true

ArrayJoin:
  Description: 'Use Array#join instead of Array#*.'
  Enabled: false

AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  Enabled: false

AsciiIdentifiers:
  Description: 'Use only ascii symbols in identifiers.'
  Enabled: false

Attr:
  Description: 'Checks for uses of Module#attr.'
  Enabled: false

BeginBlock:
  Description: 'Avoid the use of BEGIN blocks.'
  Enabled: false

BlockComments:
  Description: 'Do not use block comments.'
  Enabled: true

BlockNesting:
  Description: 'Avoid excessive block nesting'
  Enabled: false

Blocks:
  Description: >-
                Avoid using {...} for multi-line blocks (multiline chaining is
                always ugly).
                Prefer {...} over do...end for single-line blocks.
  Enabled: true

BracesAroundHashParameters:
  # Valid values are: braces, no_braces
  EnforcedStyle: no_braces
  Enabled: true

CaseEquality:
  Description: 'Avoid explicit use of the case equality operator(===).'
  Enabled: false

CaseIndentation:
  Description: 'Indentation of when in a case/when/[else/]end.'
  Enabled: false

CharacterLiteral:
  Description: 'Checks for uses of character literals.'
  Enabled: false

ClassAndModuleCamelCase:
  Description: 'Use CamelCase for classes and modules.'
  Enabled: true

ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false

ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Enabled: false

ClassMethods:
  Description: 'Use self when defining module/class methods.'
  Enabled: true

ClassVars:
  Description: 'Avoid the use of class variables.'
  Enabled: false

CollectionMethods:
  Description: 'Preferred collection methods.'
  Enabled: false

ColonMethodCall:
  Description: 'Do not use :: for method call.'
  Enabled: true

CommentAnnotation:
  Description: >-
                 Checks formatting of special comments
                 (TODO, FIXME, OPTIMIZE, HACK, REVIEW).
  Enabled: false

ConstantName:
  Description: 'Constants should use SCREAMING_SNAKE_CASE.'
  Enabled: true

CyclomaticComplexity:
  Description: 'Avoid complex methods.'
  Enabled: false

DefWithParentheses:
  Description: 'Use def with parentheses when there are arguments.'
  Enabled: true

DefWithoutParentheses:
  Description: >
                 Omit the parentheses when the method doesn't accept
                 any arguments.
  Enabled: true

DeprecatedHashMethods:
  Description: 'Checks for use of deprecated Hash methods.'
  Enabled: false

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  Style: 'leading'
  Enabled: false

DoubleNegation:
  Description: 'Checks for uses of double negation (!!).'
  Enabled: false

EmptyLineBetweenDefs:
  Description: 'Use empty lines between defs.'
  Enabled: true

EmptyLines:
  Description: "Don't use several empty lines in a row."
  Enabled: true

EmptyLinesAroundAccessModifier:
  Description: "Keep blank lines around access modifiers."
  Enabled: false

EmptyLinesAroundBody:
  Description: "Keeps track of empty lines around expression bodies."
  Enabled: false

EmptyLiteral:
  Description: 'Prefer literals to Array.new/Hash.new/String.new.'
  Enabled: false

Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

EndBlock:
  Description: 'Avoid the use of END blocks.'
  Enabled: false

EndOfLine:
  Description: 'Use Unix-style line endings.'
  Enabled: true

EvenOdd:
  Description: 'Favor the use of Fixnum#even? && Fixnum#odd?'
  Enabled: false

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: false

FinalNewline:
  Description: 'Checks for a final newline in a source file.'
  Enabled: true

FlipFlop:
  Description: 'Checks for flip flops'
  Enabled: false

For:
  Description: 'Checks use of for or each in multiline loops.'
  Enabled: false

FormatString:
  Description: 'Enforce the use of Kernel#sprintf, Kernel#format or String#%.'
  Enabled: false

GlobalVars:
  Description: 'Do not introduce global variables.'
  Enabled: false

HashSyntax:
  Description: >
                 Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax
                 { :a => 1, :b => 2 }.
  EnforcedStyle: ruby19
  Enabled: true

IfUnlessModifier:
  Description: >-
                 Favor modifier if/unless usage when you have a
                 single-line body.
  Enabled: false

IfWithSemicolon:
  Description: 'Never use if x; .... Use the ternary operator instead.'
  Enabled: true

IndentationConsistency:
  Description: 'Keep indentation straight.'
  Enabled: fals

IndentationWidth:
  Description: 'Use 2 spaces for indentation.'
  Enabled: true

IndentArray:
  Description: >-
                 Checks the indentation of the first element in an array
                 literal.
  Enabled: false

IndentHash:
  Description: 'Checks the indentation of the first key in a hash literal.'
  Enabled: false

Lambda:
  Description: 'Use the new lambda literal syntax for single-line blocks.'
  Enabled: false

LambdaCall:
  Description: 'Use lambda.call(...) instead of lambda.(...).'
  Enabled: false

LeadingCommentSpace:
  Description: 'Comments should start with a space.'
  Enabled: false

LineEndConcatenation:
  Description: >-
                 Use \ instead of + or << to concatenate two string literals at
                 line end.
  Enabled: false

LineLength:
  Description: 'Limit lines to 80 characters.'
  Max: 80
  Enabled: true

MethodCallParentheses:
  Description: 'Do not use parentheses for method calls with no arguments.'
  Enabled: true

MethodDefParentheses:
  Description: >-
                 Checks if the method definitions have or don't have
                 parentheses.
  Enabled: false

MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Enabled: false

MethodName:
  # Valid values are: snake_case, camelCase
  Description: 'Use the configured style when naming methods.'
  EnforcedStyle: snake_case
  Enabled: true

ModuleFunction:
  Description: 'Checks for usage of `extend self` in modules.'
  Enabled: false

MultilineBlockChain:
  Description: 'Avoid multi-line chains of blocks.'
  Enabled: false

MultilineIfThen:
  Description: 'Never use then for multi-line if/unless.'
  Enabled: false

MultilineTernaryOperator:
  Description: >-
                 Avoid multi-line ?: (the ternary operator);
                 use if/unless instead.
  Enabled: false

NegatedIf:
  Description: >-
                 Favor unless over if for negative conditions
                 (or control flow or).
  Enabled: false

NegatedWhile:
  Description: 'Favor until over while for negative conditions.'
  Enabled: false

NestedTernaryOperator:
  Description: 'Use one expression per branch in a ternary operator.'
  Enabled: false

NilComparison:
  Description: 'Prefer x.nil? to x == nil.'
  Enabled: false

NonNilCheck:
  Description: 'Checks for redundant nil checks.'
  Enabled: false

Not:
  Description: 'Use ! instead of not.'
  Enabled: true

NumericLiterals:
  Description: >-
                 Add underscores to large numeric literals to improve their
                 readability.
  Enabled: false

OneLineConditional:
  Description: >-
                 Favor the ternary operator(?:) over
                 if/then/else/end constructs.
  Enabled: false

OpMethod:
  Description: 'When defining binary operators, name the argument other.'
  Enabled: false

ParameterLists:
  Description: 'Avoid parameter lists longer than three or four parameters.'
  Enabled: false

ParenthesesAroundCondition:
  Description: >
                 Don't use parentheses around the condition of an
                 if/unless/while.
  Enabled: true

PercentLiteralDelimiters:
  Description: 'Use `%`-literal delimiters consistently'
  Enabled: false

PerlBackrefs:
  Description: 'Avoid Perl-style regex back references.'
  Enabled: false

PredicateName:
  Description: 'Check the names of predicate methods.'
  Enabled: false

Proc:
  Description: 'Use proc instead of Proc.new.'
  Enabled: false

RaiseArgs:
  Description: 'Checks the arguments passed to raise/fail.'
  Enabled: false

ReduceArguments:
  Description: 'Name reduce arguments |a, e| (accumulator, element)'
  Enabled: true

RedundantBegin:
  Description: "Don't use begin blocks when they are not needed."
  Enabled: true

RedundantException:
  Description: "Checks for an obsolete RuntimeException argument in raise/fail."
  Enabled: false

RedundantReturn:
  Description: "Don't use return where it's not required."
  Enabled: true

RedundantSelf:
  Description: "Don't use self where it's not needed."
  Enabled: true

RegexpLiteral:
  Description: >-
                 Use %r for regular expressions matching more than
                 `MaxSlashes` '/' characters.
                 Use %r only for regular expressions matching more than
                 `MaxSlashes` '/' character.
  Enabled: false

RescueModifier:
  Description: 'Avoid using rescue in its modifier form.'
  Enabled: false

SelfAssignment:
  Description: 'Checks for places where self-assignment shorthand should have been used.'
  Enabled: false

Semicolon:
  Description: "Don't use semicolons to terminate expressions."
  Enabled: false

SignalException:
  Description: 'Checks for proper usage of fail and raise.'
  Enabled: false

SingleLineBlockParams:
  Description: 'Enforces the names of some block params.'
  Enabled: false

SingleLineMethods:
  Description: 'Avoid single-line methods.'
  Enabled: false

SingleSpaceBeforeFirstArg:
  Description: >-
                 Checks that exactly one space is used between a method name
                 and the first argument for method calls without parentheses.
  Enabled: false

SpaceAfterColon:
  Description: 'Use spaces after colons.'
  Enabled: true

SpaceAfterComma:
  Description: 'Use spaces after commas.'
  Enabled: true

SpaceAfterControlKeyword:
  Description: 'Use spaces after if/elsif/unless/while/until/case/when.'
  Enabled: true

SpaceAfterMethodName:
  Description: >
                 Never put a space between a method name and the opening
                 parenthesis.
  Enabled: true

SpaceAfterNot:
  Description: Tracks redundant space after the ! operator.
  Enabled: true

SpaceAfterSemicolon:
  Description: 'Use spaces after semicolons.'
  Enabled: true

SpaceBeforeBlockBraces:
  Description: >-
                 Checks that the left block brace has or doesn't have space
                 before it.
  Enabled: false

SpaceInsideBlockBraces:
  Description: >-
                 Checks that block braces have or don't have surrounding space.
                 For blocks taking parameters, checks that the left brace has
                 or doesn't have trailing space.
  Enabled: false

SpaceAroundEqualsInParameterDefault:
  Description: >
                 Use spaces around the = operator when assigning default
                 values in def params.
  Enabled: true

SpaceAroundOperators:
  Description: 'Use spaces around operators.'
  Enabled: true

SpaceBeforeModifierKeyword:
  Description: 'Put a space before the modifier keyword.'
  Enabled: true

SpaceInsideBrackets:
  Description: 'No spaces after [ or before ].'
  Enabled: true

SpaceInsideHashLiteralBraces:
  Description: "Use spaces inside hash literal braces - or don't."
  # Valid values (for both parameters) are: space, no_space
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  Enabled: true

SpaceInsideParens:
  Description: 'No spaces after ( or before ).'
  Enabled: true

SpecialGlobalVars:
  Description: 'Avoid Perl-style global variables.'
  Enabled: false

StringLiterals:
  # Valid values (denoting the preferred quote delimiters) are:
  # single_quotes, double_quotes
  EnforcedStyle: single_quotes
  Enabled: true

SymbolName:
  Description: 'Symbol literals should use snake_case.'
  Enabled: true

Tab:
  Description: 'No hard tabs.'
  Enabled: true

TrailingBlankLines:
  Description: 'Checks for superflous trailing blank lines.'
  Enabled: true

TrailingComma:
  Description: 'Checks for trailing comma in parameter lists and literals.'
  Enabled: false

TrailingWhitespace:
  Description: 'Avoid trailing whitespace.'
  Enabled: true

TrivialAccessors:
  Description: 'Prefer attr_* methods to trivial readers/writers.'
  Enabled: true

UnlessElse:
  Description: >
                 Never use unless with else. Rewrite these with the positive
                 case first.
  Enabled: true

VariableInterpolation:
  Description: >-
                 Don't interpolate global, instance and class variables
                 directly in strings.
  Enabled: true

VariableName:
  Description: 'Use the configured style when naming variables.'
  # Valid values are: snake_case, camelCase
  EnforcedStyle: snake_case
  Enabled: true

WhenThen:
  Description: 'Use when x then ... for one-line cases.'
  Enabled: false

WhileUntilDo:
  Description: 'Checks for redundant do after while or until.'
  Enabled: false

WhileUntilModifier:
  Description: >-
                 Favor modifier while/until usage when you have a
                 single-line body.
  Enabled: false

WordArray:
  Description: 'Use %w or %W for arrays of words.'
  Enabled: false

#################### Lint ################################
### Warnings

AmbiguousOperator:
  Description: >-
                 Checks for ambiguous operators in the first argument of a
                 method invocation without parentheses.
  Enabled: false

AmbiguousRegexpLiteral:
  Description: >-
                 Checks for ambiguous regexp literals in the first argument of
                 a method invocation without parenthesis.
  Enabled: false

AssignmentInCondition:
  Description: "Don't use assignment in conditions."
  Enabled: false

BlockAlignment:
  Description: 'Align block ends correctly.'
  Enabled: false

ConditionPosition:
  Description: 'Checks for condition placed in a confusing position relative to the keyword.'
  Enabled: false

Debugger:
  Description: 'Check for debugger calls.'
  Enabled: false

DeprecatedClassMethods:
  Description: 'Check for deprecated class method calls.'
  Enabled: false

ElseLayout:
  Description: 'Check for odd code arrangement in an else block.'
  Enabled: false

EmptyEnsure:
  Description: 'Checks for empty ensure block.'
  Enabled: false

EmptyInterpolation:
  Description: 'Checks for empty string interpolation.'
  Enabled: false

EndAlignment:
  Description: 'Align ends correctly.'
  Enabled: false

EndInMethod:
  Description: 'END blocks should not be placed inside method definitions.'
  Enabled: false

EnsureReturn:
  Description: 'Never use return in an ensure block.'
  Enabled: false

Eval:
  Description: 'The use of eval represents a serious security risk.'
  Enabled: false

HandleExceptions:
  Description: "Don't suppress exception."
  Enabled: false

InvalidCharacterLiteral:
  Description: >-
                 Checks for invalid character literals with a non-escaped
                 whitespace character.
  Enabled: false

LiteralInCondition:
  Description: 'Checks of literals used in conditions.'
  Enabled: false

LiteralInInterpolation:
  Description: 'Checks for literals used in interpolation.'
  Enabled: false

Loop:
  Description: >-
                 Use Kernel#loop with break rather than begin/end/until or
                 begin/end/while for post-loop tests.
  Enabled: false

ParenthesesAsGroupedExpression:
  Description: >-
                 Checks for method calls with a space before the opening
                 parenthesis.
  Enabled: false

RequireParentheses:
  Description: >-
                 Use parentheses in the method call to avoid confusion
                 about precedence.
  Enabled: false

RescueException:
  Description: 'Avoid rescuing the Exception class.'
  Enabled: false

ShadowingOuterLocalVariable:
  Description: >-
                 Do not use the same name as outer local variable
                 for block arguments or block local variables.
  Enabled: false

SpaceBeforeFirstArg:
  Description: >-
                 Put a space between a method name and the first argument
                 in a method call without parentheses.
  Enabled: false

StringConversionInInterpolation:
  Description: 'Checks for Object#to_s usage in string interpolation.'
  Enabled: false

UnderscorePrefixedVariableName:
  Description: 'Do not use prefix `_` for a variable that is used.'
  Enabled: false

UnusedBlockArgument:
  Description: 'Checks for unused block arguments.'
  Enabled: false

UnusedMethodArgument:
  Description: 'Checks for unused method arguments.'
  Enabled: false

UnreachableCode:
  Description: 'Unreachable code.'
  Enabled: false

UselessAccessModifier:
  Description: 'Checks for useless access modifiers.'
  Enabled: false

UselessAssignment:
  Description: 'Checks for useless assignment to a local variable.'
  Enabled: false

UselessComparison:
  Description: 'Checks for comparison of something with itself.'
  Enabled: false

UselessElseWithoutRescue:
  Description: 'Checks for useless `else` in `begin..end` without `rescue`.'
  Enabled: false

UselessSetterCall:
  Description: 'Checks for useless setter call to a local variable.'
  Enabled: false

Void:
  Description: 'Possible use of operator/literal/variable in void context.'
  Enabled: false

##################### Rails ##################################
#
# ActionFilter:
#   Description: 'Enforces consistent use of action filter methods.'
#   Enabled: false
#
# DefaultScope:
#   Description: 'Checks if the argument passed to default_scope is a block.'
#   Enabled: false
#
# HasAndBelongsToMany:
#   Description: 'Prefer has_many :through to has_and_belongs_to_many.'
#   Enabled: false
#
# Output:
#   Description: 'Checks for calls to puts, print, etc.'
#   Enabled: false
#
# ReadWriteAttribute:
#   Description: 'Checks for read_attribute(:attr) and write_attribute(:attr, val).'
#   Enabled: false
#
# ScopeArgs:
#   Description: 'Checks the arguments of ActiveRecord scopes.'
#   Enabled: false
#
# Validation:
#   Description: 'Use sexy validations.'
#   Enabled: false
