AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
  Exclude:
    - 'lib/adl-utils/data/**/*'
    - 'lib/adl-utils/methods/**/*'
    - 'lib/adl-utils/strategies/**/*'
DoubleNegation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  EnforcedStyle: ruby19
SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Blocks:
  Enabled: false
PerlBackrefs:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
AssignmentInCondition:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
HandleExceptions:
  Enabled: false
EndAlignment:
  AlignWith: variable
SignalException:
  Enabled: false
RegexpLiteral:
  Enabled: false
FormatString:
  Enabled: false
CaseIndentation:
  IndentWhenRelativeTo: end
TrivialAccessors:
  ExactNameMatch: true
